sources:
  - name: raw_data
    description: Raw taxi trip data from NYC TLC
    database: "{{ env_var('DBT_GCP_PROJECT_ID') }}"
    schema: nytaxi
    
    tables:
      - name: green_tripdata
        description: Raw green taxi trip records

      - name: yellow_tripdata
        description: Raw yellow taxi trip records